version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
