version: '3'

vars:
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  MODULE_NAME: 'github.com/Daniil-Sakharov/BrowserAgent'

tasks:
  # ============================================================================
  # Сборка и запуск
  # ============================================================================

  build:
    desc: "Собирает бинарник агента"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/agent ./cmd/agent
      - echo "Бинарник собран"

  run:
    desc: "Запускает агента в интерактивном режиме"
    deps: [build]
    cmds:
      - "{{.BIN_DIR}}/agent run"

  start:
    desc: "Запускает агента с задачей (task start -- 'задача')"
    deps: [build]
    cmds:
      - "{{.BIN_DIR}}/agent run '{{.CLI_ARGS}}'"

  dev:
    desc: "Запуск в режиме разработки (go run)"
    cmds:
      - go run ./cmd/agent run

  # ============================================================================
  # Форматирование и линтинг
  # ============================================================================

  format:
    desc: "Форматирует код"
    cmds:
      - go fmt ./...

  lint:
    desc: "Запускает golangci-lint"
    cmds:
      - golangci-lint run ./... --config=.golangci.yml

  check:
    desc: "Полная проверка (format + lint)"
    deps: [format, lint]
    cmds:
      - echo "Все проверки прошли"

  # ============================================================================
  # Docker
  # ============================================================================

  docker-build:
    desc: "Собирает Docker образ"
    cmds:
      - docker-compose -f deploy/compose/docker-compose.yml build

  docker-up:
    desc: "Запускает в Docker"
    cmds:
      - docker-compose -f deploy/compose/docker-compose.yml up

  docker-down:
    desc: "Останавливает Docker"
    cmds:
      - docker-compose -f deploy/compose/docker-compose.yml down

  # ============================================================================
  # Очистка
  # ============================================================================

  clean:
    desc: "Очищает собранные файлы"
    cmds:
      - rm -rf {{.BIN_DIR}}
      - go clean -cache

  default:
    desc: "Показывает список задач"
    cmds:
      - task --list
