version: '3'

# Глобальные переменные проекта AI Browser Agent
vars:
  GO_VERSION: '1.21'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  
  # Модуль проекта (для gci prefix)
  MODULE_NAME: 'github.com/Daniil-Sakharov/BrowserAgent'

tasks:
  # ============================================================================
  # Установка инструментов
  # ============================================================================
  
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.
      
      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.
      
      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  install-tools:
    desc: "Устанавливает все необходимые инструменты"
    summary: |
      Устанавливает все инструменты разработки:
        - golangci-lint: линтер
        - gofumpt: форматтер кода
        - gci: сортировщик импортов
    deps:
      - install-golangci-lint
      - install-formatters

  # ============================================================================
  # Форматирование кода
  # ============================================================================

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    summary: |
      Форматирует все Go-файлы проекта с использованием gofumpt для стандартизации кода
      и gci для сортировки импортов, исключая файлы в директориях mocks и vendor.
      
      Использует инструменты:
        - gofumpt: для стандартизации форматирования
        - gci: для сортировки импортов по стандартным группам
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        find . -type f -name '*.go' \
          ! -path './vendor/*' \
          ! -path '*/mocks/*' \
          ! -path './bin/*' \
          -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci ..."
        find . -type f -name '*.go' \
          ! -path './vendor/*' \
          ! -path '*/mocks/*' \
          ! -path './bin/*' \
          -exec {{.GCI}} write -s standard -s default -s "prefix({{.MODULE_NAME}})" {} +
      - echo "✅ Форматирование завершено"

  # ============================================================================
  # Линтинг
  # ============================================================================

  lint:
    desc: "Запускает golangci-lint для всего проекта"
    summary: |
      Запускает линтер golangci-lint для проверки кода на соответствие стандартам качества.
      Линтер проверяет:
        - Стилистику кода
        - Потенциальные баги
        - Неиспользуемый код
        - Проблемы безопасности (gosec)
        - И многое другое
      
      Зависимости:
        - install-golangci-lint: автоматически устанавливает линтер
    deps: [ install-golangci-lint ]
    cmds:
      - |
        echo "🔍 Запускаем golangci-lint ..."
        {{.GOLANGCI_LINT}} run ./... --config=.golangci.yml
      - echo "✅ Линтинг завершен"

  lint-fix:
    desc: "Запускает golangci-lint с автоисправлением"
    summary: |
      Запускает линтер с флагом --fix для автоматического исправления простых проблем.
    deps: [ install-golangci-lint ]
    cmds:
      - |
        echo "🔧 Запускаем golangci-lint с автоисправлением ..."
        {{.GOLANGCI_LINT}} run ./... --config=.golangci.yml --fix
      - echo "✅ Автоисправление завершено"

  # ============================================================================
  # Проверка качества кода (используется в CI)
  # ============================================================================

  check:
    desc: "Полная проверка качества кода (format + lint)"
    summary: |
      Выполняет полную проверку качества кода:
        1. Форматирование кода
        2. Линтинг
      
      Эта задача используется в CI/CD для проверки перед merge.
    deps:
      - format
      - lint
    cmds:
      - echo "✅ Все проверки прошли успешно!"

  # ============================================================================
  # Сборка и запуск
  # ============================================================================

  build:
    desc: "Собирает бинарник агента"
    summary: |
      Компилирует проект и создает исполняемый файл в директории bin.
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - |
        echo "🔨 Собираем бинарник ..."
        go build -o {{.BIN_DIR}}/agent ./cmd/agent
      - echo "✅ Бинарник собран: {{.BIN_DIR}}/agent"

  run:
    desc: "Запускает агента с тестовой задачей"
    summary: |
      Быстрый запуск агента для тестирования.
      Использование: task run TASK="Ваша задача"
    deps: [ build ]
    cmds:
      - |
        {{if .TASK}}
          echo "🤖 Запускаем агента с задачей: {{.TASK}}"
          {{.BIN_DIR}}/agent run "{{.TASK}}"
        {{else}}
          echo "❌ Укажите задачу через переменную TASK"
          echo "Пример: task run TASK='Открой google.com'"
          exit 1
        {{end}}

  # ============================================================================
  # Очистка
  # ============================================================================

  clean:
    desc: "Очищает собранные файлы и зависимости"
    summary: |
      Удаляет:
        - Собранные бинарники
        - Скачанные инструменты
        - Временные файлы
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf vendor
      - go clean -cache -testcache -modcache
      - echo "✅ Очистка завершена"

  # ============================================================================
  # Помощь
  # ============================================================================

  default:
    desc: "Показывает список доступных задач"
    cmds:
      - task --list
